### ISSUE TITLE
Bancheck - Key missing with no channel set

### ISSUE THREAD

**Issue by aikaterna** [Bakersbakebread/Bread-Cogs#1]
Fresh install of bancheck - channel was not set yet. On a server join we have this exception:
![screenshot_2017-09-25-10-12-34-1-1](https://user-images.githubusercontent.com/20862007/30864371-3e56a80e-a288-11e7-9fd4-ce12f14a5150.png)

**Comment by ghost** [comment]
First off, have you set your token for dbans?

**Comment by aikaterna** [comment]
It's a key error for the toggle since defaults were not set in the json on cog load.
