### ISSUE TITLE
Incorrect Regex

### ISSUE THREAD

**Issue by ghost** [Bakersbakebread/Bread-Cogs#3]
Regex on this file is incorrect and will not allow proof to show

**Comment by Bakersbakebread** [comment]
![image](https://user-images.githubusercontent.com/29239704/31861637-d4abc956-b728-11e7-84a5-2817df0a2e48.png)

Clicking on proof here will deliver this url:

![image](https://user-images.githubusercontent.com/29239704/31861643-e5edbdc8-b728-11e7-90f2-3f86ce46cf19.png)


The issue I believe you are experiencing is from incorrect URL format from the submitted user, not the regex. I have not been able to replicate any problems with the Regex, only with invalid links - something out of my control. If you are able to recreate and can provide a little bit more of an insight as to what is "incorrect" please open another issue.
